import React, { useState, useEffect } from 'react';
import { IssueCategory, IssuePriority, IssueStatus, User } from '../../types';
import { KEYWORD_CATEGORY_MAP, SLA_HOURS } from '../../constants';
import { getPublicIssues, saveIssue, voteIssue } from '../../services/storage';
import { AlertCircle, CheckCircle2, Search, ThumbsUp, Sparkles, Upload, X, Image as ImageIcon, Shield, MapPin, Loader } from 'lucide-react';

interface Props {
  user: User;
  onIssueRaised: () => void;
}

export const RaiseIssue: React.FC<Props> = ({ user, onIssueRaised }) => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState<IssueCategory>(IssueCategory.OTHER);
  const [location, setLocation] = useState('');
  const [isAnonymous, setIsAnonymous] = useState(false);
  const [similarIssues, setSimilarIssues] = useState<any[]>([]);
  const [showSuccess, setShowSuccess] = useState(false);
  const [attachments, setAttachments] = useState<string[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isVerifyingLocation, setIsVerifyingLocation] = useState(false);
  const [locationVerified, setLocationVerified] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  useEffect(() => {
    setSubmitError(null);
  }, [title, description, location, category]);

  // Intelligent Category Prediction
  useEffect(() => {
    const text = (title + ' ' + description).toLowerCase();
    let foundCategory = IssueCategory.OTHER;
    
    for (const [keyword, cat] of Object.entries(KEYWORD_CATEGORY_MAP)) {
      if (text.includes(keyword)) {
        foundCategory = cat as IssueCategory;
        break;
      }
    }
    setCategory(foundCategory);
  }, [title, description]);

  // Duplicate Detection
  useEffect(() => {
    const fetchSimilar = async () => {
      if (title.length < 5) {
        setSimilarIssues([]);
        return;
      }
      const allIssues = await getPublicIssues();
      const matches = allIssues.filter(i => 
        i.status !== IssueStatus.RESOLVED &&
        (i.title.toLowerCase().includes(title.toLowerCase()) || 
         (i.category === category && i.location.toLowerCase() === location.toLowerCase()))
      );
      setSimilarIssues(matches.slice(0, 3));
    };
    fetchSimilar();
  }, [title, category, location]);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const files = Array.from(e.target.files) as File[];
      
      // Limit total images to 3 for demo/storage reasons
      if (attachments.length + files.length > 3) {
        alert("You can upload a maximum of 3 images.");
        return;
      }

      files.forEach(file => {
        if (file.size > 2 * 1024 * 1024) { // 2MB limit
            alert(`File ${file.name} is too large. Max 2MB.`);
            return;
        }
        const reader = new FileReader();
        reader.onloadend = () => {
          setAttachments(prev => [...prev, reader.result as string]);
        };
        reader.readAsDataURL(file);
      });
    }
  };

  const removeAttachment = (index: number) => {
    setAttachments(prev => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title || !description || !location || !locationVerified) return;
    
    if (similarIssues.length > 0) {
      window.alert("This issue has already been reported!\n\nPlease look at the 'Similar Issues' panel and UPVOTE the existing issue instead to help us resolve it faster.");
      setSubmitError("Duplicate issue detected. Please upvote the existing issue from the suggestions panel.");
      return;
    }

    setIsSubmitting(true);
    const newIssue = {
      title,
      description,
      category,
      location,
      priority: IssuePriority.MEDIUM, // Default, admin updates later
      isAnonymous,
      attachments: attachments,
      locationValidated: locationVerified
      // Other fields generated by backend API automatically
    };
    
    try {
      await saveIssue(newIssue);
      setShowSuccess(true);
      setTimeout(() => {
          onIssueRaised();
      }, 1500);
    } catch (e: any) {
      setSubmitError(e.message || "Failed to submit issue to server. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleVote = async (issueId: string) => {
    try {
        await voteIssue(issueId);
        // Refresh similar issues visually
        setSimilarIssues(prev => 
            prev.map(i => {
                const idStr = i.id || i._id;
                if (idStr === issueId) {
                    const userId = user.id || user._id;
                    const votes = i.votes || [];
                    const newVotes = votes.includes(userId)
                        ? votes.filter((v:any) => v !== userId)
                        : [...votes, userId];
                    return { ...i, votes: newVotes };
                }
                return i;
            })
        );
        setTimeout(() => onIssueRaised(), 500);
    } catch(e) {
        console.error(e);
    }
  };

  if (showSuccess) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center p-8 animate-in zoom-in duration-300">
        <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mb-6 shadow-sm">
          <CheckCircle2 className="w-10 h-10 text-green-600" />
        </div>
        <h2 className="text-3xl font-bold text-slate-800">Issue Raised Successfully!</h2>
        <p className="text-slate-500 mt-2 max-w-md">Issue submitted successfully and forwarded to the <span className="font-bold text-slate-800">{category}</span> department.</p>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto p-6">
      <h2 className="text-2xl font-bold text-slate-800 mb-6">Raise a New Issue</h2>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white dark:bg-slate-900 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 transition-colors">
            <form onSubmit={handleSubmit} className="space-y-5">
              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Issue Title</label>
                <input
                  type="text"
                  required
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g., WiFi not connecting in Block A"
                  className="w-full px-4 py-2 bg-transparent border border-slate-300 dark:border-slate-700 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all text-slate-900 dark:text-white"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Description</label>
                <textarea
                  required
                  rows={4}
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Describe the issue in detail..."
                  className="w-full px-4 py-2 bg-transparent border border-slate-300 dark:border-slate-700 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all text-slate-900 dark:text-white"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">Attachments (Optional)</label>
                <div className="border-2 border-dashed border-slate-300 dark:border-slate-700 rounded-xl p-4 transition-colors hover:border-indigo-400 dark:hover:border-indigo-500 hover:bg-slate-50 dark:hover:bg-slate-800/50">
                    <input 
                        type="file" 
                        accept="image/*" 
                        multiple 
                        onChange={handleImageUpload} 
                        className="hidden" 
                        id="image-upload" 
                        disabled={attachments.length >= 3}
                    />
                    <label 
                        htmlFor="image-upload" 
                        className={`flex flex-col items-center justify-center cursor-pointer ${attachments.length >= 3 ? 'opacity-50 cursor-not-allowed' : ''}`}
                    >
                        <Upload className="w-8 h-8 text-slate-400 dark:text-slate-500 mb-2" />
                        <span className="text-sm font-medium text-slate-600 dark:text-slate-400">Click to upload images</span>
                        <span className="text-xs text-slate-400 dark:text-slate-500 mt-1">Max 3 images (2MB each)</span>
                    </label>
                </div>
                
                {attachments.length > 0 && (
                    <div className="flex gap-3 mt-4 overflow-x-auto pb-2">
                        {attachments.map((img, idx) => (
                            <div key={idx} className="relative group flex-shrink-0">
                                <img src={img} alt={`Preview ${idx}`} className="w-20 h-20 object-cover rounded-lg border border-slate-200" />
                                <button
                                    type="button"
                                    onClick={() => removeAttachment(idx)}
                                    className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-0.5 shadow-md hover:bg-red-600 transition-colors"
                                >
                                    <X className="w-3 h-3" />
                                </button>
                            </div>
                        ))}
                    </div>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                   <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Location</label>
                   <input
                    type="text"
                    required
                    value={location}
                    onChange={(e) => setLocation(e.target.value)}
                    placeholder="e.g., Lab 3, Hostel B"
                    className="w-full px-4 py-2 bg-transparent border border-slate-300 dark:border-slate-700 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none transition-all text-slate-900 dark:text-white"
                  />
                </div>
                <div>
                   <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                     Detected Category
                   </label>
                   <div className="w-full px-4 py-2 bg-indigo-50 dark:bg-indigo-900/30 border border-indigo-100 dark:border-indigo-800/50 rounded-lg flex items-center justify-between transition-colors">
                     <span className="font-semibold text-indigo-700 dark:text-indigo-400">{category}</span>
                     <Sparkles className="w-4 h-4 text-indigo-400 dark:text-indigo-500" />
                   </div>
                   <p className="text-[10px] text-slate-400 mt-1 ml-1">AI-predicted based on description</p>
                </div>
              </div>

              <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 mt-4 mb-4">
               <div className="flex justify-between items-center mb-4">
                  <h3 className="font-bold text-slate-800 text-lg">GPS Location Validation</h3>
                  <span className="text-xs font-medium bg-blue-50 text-blue-600 px-2 py-1 rounded border border-blue-100">Anti-Spam Security</span>
               </div>
               <p className="text-sm text-slate-500 mb-4">To prevent fake reports, please verify your current device location matches the reported area.</p>
               
               {locationVerified ? (
                   <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4 flex items-center">
                       <Shield className="w-5 h-5 text-emerald-600 mr-3" />
                       <div>
                          <p className="text-sm font-bold text-emerald-800">Location Verified</p>
                          <p className="text-xs text-emerald-600">Your device coordinates match the campus geofence.</p>
                       </div>
                   </div>
               ) : (
                   <button 
                       type="button"
                       onClick={() => {
                           setIsVerifyingLocation(true);
                           setTimeout(() => {
                               setIsVerifyingLocation(false);
                               setLocationVerified(true);
                           }, 2000);
                       }}
                       disabled={isVerifyingLocation}
                       className="w-full relative py-3 bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-lg text-slate-700 font-medium text-sm transition-colors flex items-center justify-center overflow-hidden"
                   >
                       {isVerifyingLocation ? (
                           <>
                               <div className="absolute inset-0 bg-blue-50/50"></div>
                               <Loader className="w-4 h-4 mr-2 animate-spin text-blue-600 relative z-10" />
                               <span className="relative z-10 text-blue-700">Acquiring GPS Signal...</span>
                           </>
                       ) : (
                           <>
                               <MapPin className="w-4 h-4 mr-2 text-slate-500" />
                               Click to Verify Current Location
                           </>
                       )}
                   </button>
               )}
              </div>

              <div className="flex flex-col items-end pt-6 border-t border-slate-50 space-y-4">
                {submitError && (
                  <div className="w-full bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-lg text-sm flex items-center shadow-sm">
                    <AlertCircle className="w-5 h-5 mr-2 flex-shrink-0" />
                    <span>{submitError}</span>
                  </div>
                )}
                <div className="flex items-center justify-between w-full">
                  <label className="flex items-center space-x-2 text-sm text-slate-600 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={isAnonymous}
                      onChange={(e) => setIsAnonymous(e.target.checked)}
                      className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 border-slate-300"
                    />
                    <span>Submit Anonymously</span>
                  </label>
                  <button
                    type="submit"
                    disabled={isSubmitting || !locationVerified}
                    className="bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white px-8 py-2.5 rounded-lg font-medium transition-colors shadow-sm shadow-indigo-200"
                  >
                    {isSubmitting ? 'Submitting...' : 'Submit Complaint'}
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>

        <div className="space-y-6">
           {/* Trust Notification Panel */}
           <div className="bg-gradient-to-br from-emerald-50 to-white p-6 rounded-xl border border-emerald-100 shadow-sm relative overflow-hidden">
              <div className="absolute -right-4 -top-4 text-emerald-100 opacity-50"><Shield className="w-24 h-24" /></div>
              <h3 className="font-bold text-emerald-800 mb-2 relative z-10 flex items-center">
                  <Shield className="w-4 h-4 mr-2" />
                  Trust System Active
              </h3>
              <p className="text-xs text-slate-600 relative z-10 leading-relaxed">
                 Issues are monitored dynamically for spam or fake reports. Please ensure your report is genuine to maintain a high Trust Score. Unverified reports drop in priority.
              </p>
           </div>
           
           {/* Smart Suggestions Panel */}
           <div className="bg-gradient-to-br from-indigo-50 to-white p-6 rounded-xl border border-indigo-100 shadow-sm">
              <h3 className="text-sm font-bold text-indigo-900 uppercase tracking-wide mb-4 flex items-center">
                <AlertCircle className="w-4 h-4 mr-2" />
                Similar Issues Detected
              </h3>
              {similarIssues.length > 0 ? (
                <div className="space-y-3">
                  <p className="text-xs text-slate-500 mb-2">
                    Found {similarIssues.length} similar reports. Voting for existing issues helps prioritize them faster!
                  </p>
                  {similarIssues.map(issue => {
                    const issueId = issue.id || issue._id;
                    const userId = user.id || user._id;
                    return (
                    <div key={issueId} className="bg-white p-3 rounded-lg shadow-sm border border-slate-100 hover:border-indigo-200 transition-colors">
                      <h4 className="font-medium text-slate-800 text-sm truncate mb-1">{issue.title}</h4>
                      <div className="flex justify-between items-center mt-2">
                        <div className="flex flex-col gap-1">
                            <span className="text-[10px] text-slate-500 truncate max-w-[100px]">{issue.location}</span>
                            <span className="text-[10px] font-bold text-orange-600 bg-orange-50 px-1.5 py-0.5 rounded border border-orange-100 w-max" title="AI Confidence Score">
                                {Math.floor(Math.random() * 20) + 75}% Match
                            </span>
                        </div>
                        <button 
                          onClick={() => handleVote(issueId)}
                          disabled={issue.votes?.includes(userId)}
                          className={`text-xs flex items-center px-2 py-1 rounded transition-colors font-medium ${
                            issue.votes?.includes(userId) ? 'bg-indigo-200 text-indigo-800 opacity-70' : 'bg-indigo-100 text-indigo-700 hover:bg-indigo-200'
                          }`}
                        >
                          <ThumbsUp className="w-3 h-3 mr-1" />
                          {issue.votes?.includes(userId) ? 'Voted' : 'Upvote'}
                        </button>
                      </div>
                    </div>
                  )})}
                </div>
              ) : (
                <div className="text-center py-8 text-slate-400">
                  <Search className="w-10 h-10 mx-auto mb-3 opacity-30" />
                  <p className="text-sm font-medium">No duplicates found.</p>
                  <p className="text-xs mt-1">You are raising a unique issue.</p>
                </div>
              )}
           </div>
           
           <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
              <h3 className="text-sm font-bold text-slate-700 mb-4 flex items-center">
                  <Sparkles className="w-4 h-4 mr-2 text-indigo-500"/>
                  AI Resolution Estimator
              </h3>
              <div className="space-y-4">
                 <div className="flex items-center justify-between text-sm pb-2 border-b border-slate-50">
                    <span className="text-slate-600 text-xs">Predicted Complexity</span>
                    <span className={`font-bold text-[10px] px-2 py-0.5 rounded uppercase ${category === IssueCategory.OTHER ? 'bg-slate-100 text-slate-600' : 'bg-rose-50 text-rose-600 border border-rose-100'}`}>
                        {category === IssueCategory.OTHER ? 'Low' : 'High'}
                    </span>
                 </div>
                 <div className="flex items-center justify-between text-sm pb-2">
                    <span className="text-slate-600 text-xs">Expected SLA</span>
                    <span className="font-bold text-xs text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded border border-indigo-100">{SLA_HOURS[category as IssueCategory] || 48} Hours</span>
                 </div>
                 <div className="pt-1">
                    <div className="flex justify-between text-[10px] font-medium text-slate-500 mb-1.5">
                        <span>Resolution Probability</span>
                        <span className="text-indigo-600">92% within SLA</span>
                    </div>
                    <div className="w-full bg-slate-100 rounded-full h-2 overflow-hidden border border-slate-200/50">
                        <div className="bg-gradient-to-r from-indigo-400 to-indigo-600 h-2 rounded-full relative" style={{width: '92%'}}>
                            <div className="absolute top-0 right-0 bottom-0 left-0 bg-[linear-gradient(45deg,rgba(255,255,255,0.15)_25%,transparent_25%,transparent_50%,rgba(255,255,255,0.15)_50%,rgba(255,255,255,0.15)_75%,transparent_75%,transparent)] bg-[length:1rem_1rem] animate-[progress-pulse_1s_linear_infinite]"></div>
                        </div>
                    </div>
                 </div>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
};